using System.Text;
using ChatGPTWrapper.Adventure.Models;

namespace ChatGPTWrapper.Adventure.Services;

internal static class EntityInternalStateFormatGenerator
{
    public const string FileName = SectionSchema.EntityStateFormatFile;

    public static string Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Entity state format reference");
        sb.AppendLine();
        sb.AppendLine("> **Purpose:** Model-facing schema for **`entity-state.json`** — mutable play state (mood, injuries, trust, quest progress, …) separate from canon profile in **`entities.json`**.");
        sb.AppendLine(">");
        sb.AppendLine("> **Maintenance:** Auto-generated from the wrapper internal-state schema. Do not edit by hand — use **Generate reference files** on Design → Sources or **Refresh export** in Source Manager.");
        sb.AppendLine();
        AppendQuickRules(sb);
        sb.AppendLine();
        AppendUploadGuidance(sb);
        sb.AppendLine();
        sb.AppendLine("## Kind schemas");
        sb.AppendLine();

        foreach (var kindId in EntityInternalStateKind.PlayTracked.OrderBy(k => k, StringComparer.OrdinalIgnoreCase))
        {
            AppendKindSection(sb, kindId);
            sb.AppendLine();
        }

        sb.AppendLine($"_Schema version: {EntityInternalStateDocument.CurrentSchemaVersion}. Generated by ChatGPT Wrapper._");
        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static void AppendQuickRules(StringBuilder sb)
    {
        sb.AppendLine("## Quick rules");
        sb.AppendLine();
        sb.AppendLine("1. **Canon vs state** — stable identity and biography live in `entities.json`; mood, trust, injuries, and scene facts live here.");
        sb.AppendLine("2. **Patch only changes** — utility job `propose_entity_state` sends partial nested objects; omit empty blocks.");
        sb.AppendLine("3. **Paths** — use dotted paths (`emotional.mood`, `social.trustTowardPlayer`, `presence.currentLocation`).");
        sb.AppendLine("4. **Types** — string (narrative phrasing), bool, string[], or string{} dictionaries as noted per field.");
        sb.AppendLine("5. **Do not** rewrite canon description, role, or biography via state patches.");
    }

    private static void AppendUploadGuidance(StringBuilder sb)
    {
        sb.AppendLine("## Upload to Project");
        sb.AppendLine();
        sb.AppendLine("- Upload **`entity-state-format.md`** with `canon-format.md` and lore when using `propose_entity_state` during play.");
        sb.AppendLine("- In the wrapper: **Designer → Sources → Generate reference files**, or **Source Manager → Refresh export**.");
        sb.AppendLine("- Mark **Published** in Source Manager after upload.");
    }

    private static void AppendKindSection(StringBuilder sb, string kindId)
    {
        var sections = EntityInternalStateSchema.GetSections(kindId);
        sb.AppendLine($"### `{kindId}`");
        sb.AppendLine();
        sb.AppendLine("| Path | Label | Type |");
        sb.AppendLine("|------|-------|------|");

        foreach (var section in sections.OrderBy(s => s.Order))
        {
            foreach (var field in section.Fields.OrderBy(f => f.Order))
            {
                sb.AppendLine($"| `{field.Path}` | {field.Label} | {FormatFieldKind(field.Kind)} |");
            }
        }
    }

    private static string FormatFieldKind(EntityInternalStateFieldKind kind) => kind switch
    {
        EntityInternalStateFieldKind.Bool => "bool",
        EntityInternalStateFieldKind.StringList => "string[]",
        EntityInternalStateFieldKind.StringDictionary => "string{}",
        _ => "string",
    };
}
