using System.Text;

using ChatGPTWrapper.Adventure.Services;



namespace ChatGPTWrapper.Adventure.Services.NarratorScales;



internal static class NarratorScalesGenerator

{

    public const string FileName = SectionSchema.NarratorScalesFile;



    /// <summary>

    /// Catalog-only reference for Project Files. Active selectors live in wrapper metadata

    /// and are injected on each play send — not embedded in this file.

    /// </summary>

    public static string Generate()

    {

        var catalog = NarratorScalesLoader.Catalog;

        var sb = new StringBuilder();



        sb.AppendLine("# Narrator scales reference");

        sb.AppendLine();

        sb.AppendLine("> **Purpose:** Canonical definitions for **narration** (delivery) and **combat** (challenge, violence) presets. Upload this file once to **ChatGPT Project → Files** alongside lore sources.");

        sb.AppendLine(">");

        sb.AppendLine("> **Maintenance:** Auto-generated from the wrapper narrator scales catalog. Do not edit by hand — use **Refresh export** in Designer or Source Manager when the catalog updates.");

        sb.AppendLine(">");

        sb.AppendLine("> **Active settings:** Adventure/session/turn selectors are **not** stored here. The wrapper injects them on each play send (and in Project instructions). Use this file only to look up what each preset **means**.");

        sb.AppendLine();

        AppendInspectInstructions(sb);

        sb.AppendLine();

        AppendHowToUse(sb);

        sb.AppendLine();

        AppendQuickReference(sb);

        sb.AppendLine();

        AppendCategoryDimensions(sb, catalog, NarratorScaleCategory.Narration, "narration-scales");

        sb.AppendLine();

        AppendCategoryDimensions(sb, catalog, NarratorScaleCategory.Combat, "combat-scales");

        sb.AppendLine();

        AppendSceneProfiles(sb, catalog);

        sb.AppendLine();

        AppendOverrideSemantics(sb);

        sb.AppendLine();

        AppendUploadGuidance(sb);

        sb.AppendLine();

        sb.AppendLine($"_Schema version: {catalog.Version}. Generated by ChatGPT Wrapper._");



        return sb.ToString().TrimEnd() + Environment.NewLine;

    }



    private static void AppendInspectInstructions(StringBuilder sb)

    {

        sb.AppendLine("## inspect-instructions");

        sb.AppendLine();

        sb.AppendLine(NarratorScalesResolver.BuildInspectInstructions());

        sb.AppendLine();

        sb.AppendLine("**Required workflow:**");

        sb.AppendLine();

        sb.AppendLine("1. Read the `=== ACTIVE NARRATOR SCALES ===` block in the play packet (or Project custom instructions) for **which** preset is active on each dimension.");

        sb.AppendLine("2. For each listed selector (e.g. `Combat difficulty: balanced`), **open this file** and find `### combat-difficulty` → `#### balanced`.");

        sb.AppendLine("3. Read **Summary**, **Narration behavior**, and **Avoid** for that preset — apply all bullets.");

        sb.AppendLine("4. For turn/session overrides in `=== TURN OVERRIDES ===`, apply the override preset on top of the adventure baselines from the active-scales block.");

        sb.AppendLine("5. **Violence level**, **narrative pacing**, and **consequence weight** follow the same override layers as combat difficulty.");

    }



    private static void AppendHowToUse(StringBuilder sb)

    {

        sb.AppendLine("## how-to-use");

        sb.AppendLine();

        sb.AppendLine("### Categories");

        sb.AppendLine();

        sb.AppendLine("| Category | Dimensions | Where active values live | Override in Play? |");

        sb.AppendLine("|----------|------------|--------------------------|-------------------|");

        sb.AppendLine("| **Narration (delivery)** | Response length, Detail level, Tone, Narrative pacing | Wrapper metadata + each play packet | Yes — turn/session/adventure |");

        sb.AppendLine("| **Combat & stakes** | Combat difficulty, Violence level, Consequence weight | Wrapper metadata + each play packet | Yes — turn/session/adventure |");

        sb.AppendLine();

        sb.AppendLine("### Override layers");

        sb.AppendLine();

        sb.AppendLine("1. **Adventure baseline** — Instructions designer / Play settings → Adventure default.");

        sb.AppendLine("2. **Session overrides** — Injection panel, scope **Session**.");

        sb.AppendLine("3. **Turn overrides** — Injection panel, scope **This send** (`=== TURN OVERRIDES ===`).");

        sb.AppendLine();

        sb.AppendLine("Scene profiles apply coordinated narration presets for one scope (action, exploration, social, etc.).");

    }



    private static void AppendQuickReference(StringBuilder sb)

    {

        sb.AppendLine("## quick-reference");

        sb.AppendLine();

        sb.AppendLine("This file does **not** list adventure-specific active values.");

        sb.AppendLine();

        sb.AppendLine("- **Play packets** include `=== ACTIVE NARRATOR SCALES ===` with current selectors and pointers into the dimension sections below.");

        sb.AppendLine("- **Project custom instructions** mirror adventure baselines when you sync or paste instructions from the wrapper.");

        sb.AppendLine("- Use the dimension tables in `## narration-scales` and `## combat-scales` to interpret each selector.");

    }



    private static void AppendCategoryDimensions(

        StringBuilder sb,

        NarratorScalesCatalog catalog,

        NarratorScaleCategory category,

        string sectionId)

    {

        var title = category == NarratorScaleCategory.Narration

            ? "Narration scales (delivery)"

            : "Combat scales (challenge & violence)";



        sb.AppendLine($"## {sectionId}");

        sb.AppendLine();

        sb.AppendLine($"**{title}** — definitions for the wrapper **{NarratorScaleLabels.CombatGroup}** or **{NarratorScaleLabels.NarrationGroup}** UI groups.");

        sb.AppendLine();



        foreach (var dimension in catalog.DimensionsFor(category))

        {

            AppendDimension(sb, dimension);

            sb.AppendLine();

        }

    }



    private static void AppendDimension(StringBuilder sb, NarratorScaleDimensionSpec dimension)

    {

        sb.AppendLine($"### {dimension.Id}");

        sb.AppendLine();

        sb.AppendLine($"Packet label: **{dimension.PacketLabel}**");

        sb.AppendLine($"Category: **{(dimension.Category == NarratorScaleCategory.Combat ? "Combat & stakes" : "Narration (delivery)")}**");

        sb.AppendLine();



        foreach (var preset in dimension.Presets)

            AppendPreset(sb, preset);

    }



    private static void AppendPreset(StringBuilder sb, NarratorScalePresetSpec preset)

    {

        sb.AppendLine($"#### {preset.Id}");

        sb.AppendLine();

        sb.AppendLine($"**Summary:** {preset.Summary}");

        sb.AppendLine();



        if (preset.Behavior.Count > 0)

        {

            sb.AppendLine("**Narration behavior:**");

            foreach (var line in preset.Behavior)

                sb.AppendLine($"- {line}");

            sb.AppendLine();

        }



        if (preset.Avoid.Count > 0)

        {

            sb.AppendLine("**Avoid:**");

            foreach (var line in preset.Avoid)

                sb.AppendLine($"- {line}");

            sb.AppendLine();

        }



        if (preset.PairsWellWith.Count > 0)

        {

            sb.AppendLine("**Pairs well with:** " + string.Join("; ", preset.PairsWellWith));

            sb.AppendLine();

        }

    }



    private static void AppendSceneProfiles(StringBuilder sb, NarratorScalesCatalog catalog)

    {

        sb.AppendLine("## scene-profiles");

        sb.AppendLine();

        sb.AppendLine("One-shot coordinated **narration** presets from the wrapper Injection panel:");

        sb.AppendLine();



        foreach (var profile in catalog.SceneProfiles)

        {

            sb.AppendLine($"### {profile.Id}");

            sb.AppendLine();

            sb.AppendLine($"**{profile.DisplayName}** — {profile.Description}");

            sb.AppendLine();

            foreach (var (dimensionId, presetId) in profile.Values)

            {

                var dim = catalog.TryGetDimension(dimensionId);

                var label = dim?.PacketLabel ?? dimensionId;

                sb.AppendLine($"- {label}: `{presetId}` (see ### {dimensionId} / #### {presetId})");

            }



            sb.AppendLine();

        }

    }



    private static void AppendOverrideSemantics(StringBuilder sb)

    {

        sb.AppendLine("## override-semantics");

        sb.AppendLine();

        sb.AppendLine("When a play packet includes `=== TURN OVERRIDES ===`:");

        sb.AppendLine();

        sb.AppendLine("- **Inspect this file** for each listed dimension before narrating.");

        sb.AppendLine("- Apply only the listed dimensions; others inherit from session or adventure baseline in `=== ACTIVE NARRATOR SCALES ===`.");

        sb.AppendLine("- `— inherit —` in the wrapper means no override at that scope.");

        sb.AppendLine("- Expanded override lines include a one-line summary and point to the preset section here.");

        sb.AppendLine("- Turn directives (`=== TURN DIRECTIVE ===`) take precedence over scale presets for that send.");

    }



    private static void AppendUploadGuidance(StringBuilder sb)

    {

        sb.AppendLine("## upload-to-project");

        sb.AppendLine();

        sb.AppendLine("- Upload **`narrator-scales.md`** once with `canon-format.md` and lore files (`cast.md`, `scenario.md`, etc.).");

        sb.AppendLine("- In the wrapper: **Designer → Sources** or **Source Manager → Refresh export**, then drag from the canonical folder.");

        sb.AppendLine("- Mark **Published** in Source Manager after upload.");

        sb.AppendLine("- You do **not** need to re-upload when adventure narrator settings change — the wrapper injects active selectors on each send.");

        sb.AppendLine("- Re-upload only when the wrapper catalog version changes (Refresh export updates this reference file).");

    }

}


